/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { HouseholdUser } from "./HouseholdUser";
import { HouseholdUserCountArgs } from "./HouseholdUserCountArgs";
import { HouseholdUserFindManyArgs } from "./HouseholdUserFindManyArgs";
import { HouseholdUserFindUniqueArgs } from "./HouseholdUserFindUniqueArgs";
import { DeleteHouseholdUserArgs } from "./DeleteHouseholdUserArgs";
import { HouseholdUserService } from "../householdUser.service";
@graphql.Resolver(() => HouseholdUser)
export class HouseholdUserResolverBase {
  constructor(protected readonly service: HouseholdUserService) {}

  async _householdUsersMeta(
    @graphql.Args() args: HouseholdUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [HouseholdUser])
  async householdUsers(
    @graphql.Args() args: HouseholdUserFindManyArgs
  ): Promise<HouseholdUser[]> {
    return this.service.householdUsers(args);
  }

  @graphql.Query(() => HouseholdUser, { nullable: true })
  async householdUser(
    @graphql.Args() args: HouseholdUserFindUniqueArgs
  ): Promise<HouseholdUser | null> {
    const result = await this.service.householdUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => HouseholdUser)
  async deleteHouseholdUser(
    @graphql.Args() args: DeleteHouseholdUserArgs
  ): Promise<HouseholdUser | null> {
    try {
      return await this.service.deleteHouseholdUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
