/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WasteCollectionSchedule } from "./WasteCollectionSchedule";
import { WasteCollectionScheduleCountArgs } from "./WasteCollectionScheduleCountArgs";
import { WasteCollectionScheduleFindManyArgs } from "./WasteCollectionScheduleFindManyArgs";
import { WasteCollectionScheduleFindUniqueArgs } from "./WasteCollectionScheduleFindUniqueArgs";
import { DeleteWasteCollectionScheduleArgs } from "./DeleteWasteCollectionScheduleArgs";
import { WasteCollectionScheduleService } from "../wasteCollectionSchedule.service";
@graphql.Resolver(() => WasteCollectionSchedule)
export class WasteCollectionScheduleResolverBase {
  constructor(protected readonly service: WasteCollectionScheduleService) {}

  async _wasteCollectionSchedulesMeta(
    @graphql.Args() args: WasteCollectionScheduleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WasteCollectionSchedule])
  async wasteCollectionSchedules(
    @graphql.Args() args: WasteCollectionScheduleFindManyArgs
  ): Promise<WasteCollectionSchedule[]> {
    return this.service.wasteCollectionSchedules(args);
  }

  @graphql.Query(() => WasteCollectionSchedule, { nullable: true })
  async wasteCollectionSchedule(
    @graphql.Args() args: WasteCollectionScheduleFindUniqueArgs
  ): Promise<WasteCollectionSchedule | null> {
    const result = await this.service.wasteCollectionSchedule(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WasteCollectionSchedule)
  async deleteWasteCollectionSchedule(
    @graphql.Args() args: DeleteWasteCollectionScheduleArgs
  ): Promise<WasteCollectionSchedule | null> {
    try {
      return await this.service.deleteWasteCollectionSchedule(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
