/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RecyclingTracker } from "./RecyclingTracker";
import { RecyclingTrackerCountArgs } from "./RecyclingTrackerCountArgs";
import { RecyclingTrackerFindManyArgs } from "./RecyclingTrackerFindManyArgs";
import { RecyclingTrackerFindUniqueArgs } from "./RecyclingTrackerFindUniqueArgs";
import { DeleteRecyclingTrackerArgs } from "./DeleteRecyclingTrackerArgs";
import { RecyclingTrackerService } from "../recyclingTracker.service";
@graphql.Resolver(() => RecyclingTracker)
export class RecyclingTrackerResolverBase {
  constructor(protected readonly service: RecyclingTrackerService) {}

  async _recyclingTrackersMeta(
    @graphql.Args() args: RecyclingTrackerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RecyclingTracker])
  async recyclingTrackers(
    @graphql.Args() args: RecyclingTrackerFindManyArgs
  ): Promise<RecyclingTracker[]> {
    return this.service.recyclingTrackers(args);
  }

  @graphql.Query(() => RecyclingTracker, { nullable: true })
  async recyclingTracker(
    @graphql.Args() args: RecyclingTrackerFindUniqueArgs
  ): Promise<RecyclingTracker | null> {
    const result = await this.service.recyclingTracker(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RecyclingTracker)
  async deleteRecyclingTracker(
    @graphql.Args() args: DeleteRecyclingTrackerArgs
  ): Promise<RecyclingTracker | null> {
    try {
      return await this.service.deleteRecyclingTracker(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
